cmake_minimum_required(VERSION 3.22.1)
project(ephora)
include(FetchContent)
set(BUILD_CODEC OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(BUILD_DOC OFF CACHE BOOL "" FORCE)
set(BUILD_JPIP OFF CACHE BOOL "" FORCE)
set(BUILD_MJ2 OFF CACHE BOOL "" FORCE)
set(BUILD_THIRDPARTY OFF CACHE BOOL "" FORCE)
set(WITH_ZLIB OFF CACHE BOOL "" FORCE)
set(WITH_PNG OFF CACHE BOOL "" FORCE)
set(WITH_TIFF OFF CACHE BOOL "" FORCE)
set(WITH_LCMS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(openjpeg URL https://github.com/uclouvain/openjpeg/archive/refs/tags/v2.5.2.tar.gz)
FetchContent_MakeAvailable(openjpeg)
add_library(ephora SHARED native-lib.cpp)
find_library(log-lib log)
target_link_libraries(ephora openjp2 ${log-lib})